var ObjectID = require('mongodb').ObjectID;
var express = require('express');
var router = express.Router();

/* GET event listing. */
router.get('/', function (req, res) {
  var collection = req.db.collection('events');
  collection.find().toArray(function (err, events) {
    res.json(events);
  });
});

router.get('/:id', function (req, res) {
  var collection = req.db.collection('events');
  collection.findOne({_id: ObjectID(req.params.id)}, function (err, event) {
    res.json(event);
  });
});

router.post('/', function (req, res) {
  var title = req.body.title;
  var description = req.body.description;
  var event = {
    title: title,
    description: description
  };

  var collection = req.db.collection('events');
  collection.insertOne(event, function (err, result) {
    res.json(event); // Event will have _id generated by Mongo
  })
});

module.exports = router;
